---
deploy_user: root
deploy_port: 22
deploy_key: "$HOME/.ssh/id_rsa.pub"
deploy_path: "$HOME/crypti"
crypti_path: "/install"
reference_node: 83.136.253.66
download_url: http://downloads.cryptichain.me/
genesis: 1425859200
environment: live
top_accounts: false
servers: {}
