---
deploy_path: "/var/crypti"
deploy_user: root
reference_node: 83.136.253.66
download_url: http://downloads.cryptichain.me/
genesis: 1425859200
environment: live
top_accounts: false
servers: {}
accounts: {}
