---
deploy_path: "/var/crypti"
deploy_user: root
app_url: http://storage.googleapis.com/downloads.crypti.me/crypti-node/0.1.x/0.1.9d.zip
app_version: 0.1.9d
blockchain_url: http://storage.googleapis.com/downloads.crypti.me/blockchains/blockchain.db.zip
mining_info: enabled
environment: live
servers: {}
accounts: {}
